### ISSUE TITLE
Test mode leaves ignition channels active when being stopped

### ISSUE THREAD

**Issue by ggurov** [speeduino/speeduino#1246] opened 2024-09-12 16:50 UTC
When exiting test mode using 
![image](https://github.com/user-attachments/assets/1c1c96d7-1be9-4012-80bb-ec5e90453881)

if there's an active test running, there's a chance that channel will keep its state, instead of being logic  "off".

this could totally fry some coils or flood an engine. 

![image](https://github.com/user-attachments/assets/a657b3eb-e6f6-406e-a0d8-b027df1c3647)

->

stop test mode 

->

![image](https://github.com/user-attachments/assets/33651c97-2a4f-4ea3-bcff-0c25007ffc17)

"stop test mode" should ensure all channels are turned logic "off"

**Comment by noisymime** [comment] 2024-09-19 21:30
The stop test mode button already calls `endCoilxCharge()` and `closeInjectorx()` on all channels when it's pressed so not sure how you're getting this.

What hardware are you testing on? I've tried turning the testing on/off 20-30 times on a mega2560 and can't reproduce the issue, but it's possible there may be some odd race condition occurring on other architectures.

**Comment by ggurov** [comment] 2024-09-19 21:34
it has to do with that waste spark mode in 6x3

```
    case TS_CMD_TEST_DSBL: // cmd is stop
      BIT_CLEAR(currentStatus.testOutputs, 1);
      endCoil1Charge();
      endCoil2Charge();
      endCoil3Charge();
      endCoil4Charge();
      #if IGN_CHANNELS >= 5
      endCoil5Charge();
      #endif
      #if IGN_CHANNELS >= 6
      endCoil6Charge();
      #endif
      #if IGN_CHANNELS >= 7
      endCoil7Charge();
      #endif
      #if IGN_CHANNELS >= 8
      endCoil8Charge();
      #endif
```


6x3 is possible when IGN_CHANNELS is = 3 , but there appears to be a special case handling waste spark in that mode, where it will actually turn on/off two channels with one timer, making it actually work correctly, as long as pinMode is set to output for the 5 + 6 coils. 

however, endCoil5Charge and endCoil6Charge never gets called if IGN_CHANNELS = 3

**Comment by noisymime** [comment] 2024-09-19 21:39
Ahh this is related to #1245 then. 6+3 on on a mega2560 was never intended to allow for wasted COP ignition given the 3 channels so these sorts of things are surprising. 

I'll close this for now and update #1245 accordingly

**Closed by noisymime** 2024-09-19 21:39 UTC

**Comment by ggurov** [comment] 2024-09-19 21:40
https://github.com/speeduino/speeduino/blob/master/speeduino/scheduledIO.cpp#L111-L117 it's that part that totally does 6 cyl wasted COP work.
